"""
MQL5 EA skeleton templates — hardcoded, always structurally correct.
The AST parser fills in the blanks. AI never touches these templates.
"""

EA_TEMPLATE = '''//+------------------------------------------------------------------+
//|  {ea_name}                                                       |
//|  Auto-generated by PY2MQL5 Converter                            |
//|  https://py2mql5.streamlit.app                                   |
//+------------------------------------------------------------------+
#property copyright "PY2MQL5 Converter"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>

//--- Input parameters
{input_params}

//--- Global variables
CTrade trade;
{handle_declarations}
int bar_count = 0;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
  {{
   //--- Initialize indicator handles (MUST be here, not in OnTick)
{handle_init}
   
   //--- Validate handles
{handle_validation}
   
   trade.SetExpertMagicNumber(123456);
   return(INIT_SUCCEEDED);
  }}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {{
   //--- Release indicator handles
{handle_release}
  }}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {{
   //--- Only run on new bar (H1 strategy — adjust if needed)
   if(!IsNewBar()) return;

   //--- Copy indicator buffers
{copy_buffers}
   
   //--- Current values (index 0 = current bar, 1 = previous bar)
{current_values}

   //--- Position sizing
   double lot_size = NormalizeDouble(
      AccountInfoDouble(ACCOUNT_BALANCE) * {risk_pct} / 100.0 
      / (AccountInfoDouble(ACCOUNT_MARGIN_LEVEL) + 1), 2);
   lot_size = MathMax(lot_size, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   
   //--- Check if already in position
   bool in_position = PositionSelect(_Symbol);
   
   //--- Entry Logic
{entry_logic}

   //--- Exit Logic  
{exit_logic}
  }}

//+------------------------------------------------------------------+
//| New bar detection                                                 |
//+------------------------------------------------------------------+
bool IsNewBar()
  {{
   static datetime last_bar_time = 0;
   datetime current_bar_time = iTime(_Symbol, _Period, 0);
   if(current_bar_time != last_bar_time)
     {{
      last_bar_time = current_bar_time;
      return true;
     }}
   return false;
  }}

//+------------------------------------------------------------------+
//| Calculate Stop Loss price                                         |
//+------------------------------------------------------------------+
double CalcSL(bool is_buy, double atr_value, double sl_multiplier=1.5)
  {{
   double price = is_buy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) 
                         : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl = atr_value * sl_multiplier * _Point * 
               MathPow(10, Digits() % 2);
   return is_buy ? price - sl : price + sl;
  }}

//+------------------------------------------------------------------+
//| Calculate Take Profit price                                       |
//+------------------------------------------------------------------+
double CalcTP(bool is_buy, double atr_value, double tp_multiplier=3.0)
  {{
   double price = is_buy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) 
                         : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double tp = atr_value * tp_multiplier * _Point * 
               MathPow(10, Digits() % 2);
   return is_buy ? price + tp : price - tp;
  }}
'''

# Snippets for handle declarations
HANDLE_DECL = "int handle_{name} = INVALID_HANDLE;"

HANDLE_INIT_MAP = {
    "iRSI":        'handle_{name} = iRSI(_Symbol, _Period, {p1}, PRICE_CLOSE);',
    "iMA":         'handle_{name} = iMA(_Symbol, _Period, {p1}, 0, {method}, PRICE_CLOSE);',
    "iMACD":       'handle_{name} = iMACD(_Symbol, _Period, {p1}, {p2}, {p3}, PRICE_CLOSE);',
    "iBands":      'handle_{name} = iBands(_Symbol, _Period, {p1}, 0, {p2}, PRICE_CLOSE);',
    "iATR":        'handle_{name} = iATR(_Symbol, _Period, {p1});',
    "iStochastic": 'handle_{name} = iStochastic(_Symbol, _Period, {p1}, {p2}, {p3}, MODE_SMA, STO_LOWHIGH);',
    "iADX":        'handle_{name} = iADX(_Symbol, _Period, {p1});',
    "iCCI":        'handle_{name} = iCCI(_Symbol, _Period, {p1}, PRICE_TYPICAL);',
    "iMFI":        'handle_{name} = iMFI(_Symbol, _Period, {p1}, VOLUME_TICK);',
    "iMomentum":   'handle_{name} = iMomentum(_Symbol, _Period, {p1}, PRICE_CLOSE);',
    "iWPR":        'handle_{name} = iWPR(_Symbol, _Period, {p1});',
    "iOBV":        'handle_{name} = iOBV(_Symbol, _Period, VOLUME_TICK);',
}

HANDLE_VALIDATION_SNIPPET = '''   if(handle_{name} == INVALID_HANDLE)
     {{
      Print("Failed to create {name} handle. Error: ", GetLastError());
      return(INIT_FAILED);
     }}'''

HANDLE_RELEASE_SNIPPET = "   IndicatorRelease(handle_{name});"

COPY_BUFFER_SNIPPET = '''   double {name}_buf[];
   ArraySetAsSeries({name}_buf, true);
   if(CopyBuffer(handle_{name}, {buf_index}, 0, 3, {name}_buf) < 0)
     {{
      Print("Failed to copy {name} buffer");
      return;
     }}'''

INPUT_PARAM_MAP = {
    "int":    "input int      {name} = {default};  // {comment}",
    "double": "input double   {name} = {default};  // {comment}",
    "bool":   "input bool     {name} = {default};  // {comment}",
}

DEFAULT_INPUTS = [
    ("int",    "rsi_period",    14,    "RSI Period"),
    ("int",    "ma_period",     20,    "MA Period"),
    ("double", "risk_pct",      1.0,   "Risk % per trade"),
    ("double", "sl_multiplier", 1.5,   "SL ATR multiplier"),
    ("double", "tp_multiplier", 3.0,   "TP ATR multiplier"),
]
